### ISSUE TITLE
Reuse GHCJS FFI interface

### ISSUE THREAD

**Issue by hsyl20** [tweag/asterius#303] opened 2019-09-19 11:13 UTC
Try to mimic as much as possible the GHCJS FFI interface conventions:
https://github.com/ghcjs/ghcjs/blob/master/doc/foreign-function-interface.md

**Comment by TerrorJack** [comment] 2019-10-17 02:25
Duplicate of #286; closing this one for now.

**Closed by TerrorJack** 2019-10-17 02:25 UTC
Labels: P2
