### ISSUE TITLE
[macOS] `settings` file hardcodes OSLinux and other linux specifics.

### ISSUE THREAD

**Issue by angerman** [tweag/asterius#57] opened 2019-01-12 14:56 UTC
The `settings` file in `./ghc-toolkit/ghc-libdir/settings` is for linux, and thus prevents booting on macOS outright.

A solution could be to copy the file from the custom ghc, into the `ghc-toolkit/ghc-libdir`. That one should be correct for the platform it was built on.

**Comment by TerrorJack** [comment] 2019-09-09 17:16
`settings` file might not be the only platform-specific file that chokes non-linux platforms. The root of the problem is: whatever exists in `ghc-libdir`, `include-private` and `boot-libs` directories of `ghc-toolkit` today come from various different places, either copied from ghc repo or the installed libdir in linux, and often with custom patches.

Closing this one for the moment; to improve the non-linux host platform story, we'll need to solve the bigger problem of generating appropriate boot lib sources in a principled way.

**Closed by TerrorJack** 2019-09-09 17:16 UTC

**Comment by angerman** [comment] 2019-09-10 05:24
@luite might have some experience here, especially from his recent work on windows.
